export const API_STATUS = Object.freeze({
    IDLE: "IDLE",
    SUCCEEDED: "SUCCEEDED",
    FAILED: "FAILED",
    UNAUTHORIZED: "UNAUTHORIZED",
    ACCESS_DENIED: "ACCESS_DENIED",
    PAGE_NOT_FOUND: "PAGE_NOT_FOUND",
});