version: '3.8'

networks:
  default:

services:
  db:
    image: mariadb:10.5.8
    container_name: forums-container
    ports:
    - 3306:3306
    volumes:
    - ".data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: forums